# Generated by Django 5.0.4 on 2024-04-18 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MedicoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crm", models.CharField(max_length=30)),
                ("nome_completo", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=20)),
                ("rua", models.CharField(max_length=30)),
                ("bairro", models.CharField(max_length=30)),
                ("numero", models.IntegerField()),
                ("rg", models.ImageField(upload_to="RGs")),
                ("foto_perfil", models.ImageField(upload_to="FotoPerfil")),
                (
                    "cedula_identidade_medica",
                    models.ImageField(upload_to="CedulasIdentidadeMedica"),
                ),
                ("descricao", models.TextField()),
                ("valor_consulta", models.FloatField(default=100)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="medicine.medicinearea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
